# ----
# Site

title: 
url: "http://srikrishnatraders.github.io/"
baseurl:
google_analytics_key: UA-63861353-1
google_maps_javascript_api_key:
# snipcart_key: "NWNjOWZhYjctYmE1ZS00MDM3LThkNjUtZmE5M2NiMTU1NzAwNjM2MjYzNTE1MzM5ODg1ODkw"

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Imitation Jewellery Wholesaler
author:
  name: Kishore
  email: abireddy.feb05@gmail.com
  twitter: fur # twitter username without the @ symbol
  phone: "8778569554"
social:
  name: Fur Template
  links:
    - https://github.com/CloudCannon/fur-jekyll-template

# -----
# Build
timezone: Chennai

collections:
  staff_members:
    _hide_content: true
    _icon: account_circle
  products:
    _hide_content: true
    output: true
    _icon: shopping_cart
  chains:
    _hide_content: true
    output: true
    _icon: shopping_cart
  long_chains:
    _hide_content: true
    output: true
    _icon: shopping_cart

permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "products"
    values:
      layout: "product"
  -
    scope:
      path: ""
      type: "chains"
    values:
      layout: "product"
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"

jekyll-archives:
  enabled:
    - categories

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

garment_types:
  - bangles
  - necklaces
  - earrings

social_icons:
  - Email
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Twitter

_comments:
  map: Update the map location and display settings.
  latitude: Coordinates for the center marker on the map.
  longitude: Coordinates for the center marker on the map.
  zoom: The zoom level for the map.
  pricing_table: Update the information in the pricing tables.
  highlight: Emphasis the text
  color: The background color used in the plan name and call to action.
  new_window: Open link in new window
  description: This is used for facebook shares of the page and google indexing
